[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/images/*"
to = "https://res.cloudinary.com/GESTAOBJJDOM04/image/fetch/f_auto,q_auto/https://jade-hummingbird-6d6e48.netlify.app/cld-assets/images/:splat?_a=BBFAAAAA0"
status = 302
force = true

[[redirects]]
from = "/cld-assets/images/*"
to = "/images/:splat"
status = 200
force = true

[context]

  [context.production]

  [context.master]